// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

/**
 * Protobuf type {@code Common}
 */
public final class Common extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Common)
    CommonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Common.newBuilder() to construct.
  private Common(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Common() {
    method_ = "";
    describe_ = "";
    logId_ = "";
    msgProcessFilterK_ = "";
    msgProcessFilterV_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Common();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_Common_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_Common_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.class, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.Builder.class);
  }

  private int bitField0_;
  public static final int METHOD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object method_ = "";
  /**
   * <code>string method = 1;</code>
   * @return The method.
   */
  @java.lang.Override
  public java.lang.String getMethod() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 1;</code>
   * @return The bytes for method.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodBytes() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_ID_FIELD_NUMBER = 2;
  private long msgId_ = 0L;
  /**
   * <code>uint64 msg_id = 2;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public long getMsgId() {
    return msgId_;
  }

  public static final int ROOM_ID_FIELD_NUMBER = 3;
  private long roomId_ = 0L;
  /**
   * <code>uint64 room_id = 3;</code>
   * @return The roomId.
   */
  @java.lang.Override
  public long getRoomId() {
    return roomId_;
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 4;
  private long createTime_ = 0L;
  /**
   * <code>uint64 create_time = 4;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public long getCreateTime() {
    return createTime_;
  }

  public static final int MONITOR_FIELD_NUMBER = 5;
  private int monitor_ = 0;
  /**
   * <code>uint32 monitor = 5;</code>
   * @return The monitor.
   */
  @java.lang.Override
  public int getMonitor() {
    return monitor_;
  }

  public static final int IS_SHOW_MSG_FIELD_NUMBER = 6;
  private boolean isShowMsg_ = false;
  /**
   * <code>bool is_show_msg = 6;</code>
   * @return The isShowMsg.
   */
  @java.lang.Override
  public boolean getIsShowMsg() {
    return isShowMsg_;
  }

  public static final int DESCRIBE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object describe_ = "";
  /**
   * <code>string describe = 7;</code>
   * @return The describe.
   */
  @java.lang.Override
  public java.lang.String getDescribe() {
    java.lang.Object ref = describe_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      describe_ = s;
      return s;
    }
  }
  /**
   * <code>string describe = 7;</code>
   * @return The bytes for describe.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescribeBytes() {
    java.lang.Object ref = describe_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      describe_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_TEXT_FIELD_NUMBER = 8;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text displayText_;
  /**
   * <code>.Text display_text = 8;</code>
   * @return Whether the displayText field is set.
   */
  @java.lang.Override
  public boolean hasDisplayText() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Text display_text = 8;</code>
   * @return The displayText.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getDisplayText() {
    return displayText_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : displayText_;
  }
  /**
   * <code>.Text display_text = 8;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getDisplayTextOrBuilder() {
    return displayText_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : displayText_;
  }

  public static final int FOLD_TYPE_FIELD_NUMBER = 9;
  private long foldType_ = 0L;
  /**
   * <pre>
   *  DisplayText displayText = 8;
   * </pre>
   *
   * <code>uint64 fold_type = 9;</code>
   * @return The foldType.
   */
  @java.lang.Override
  public long getFoldType() {
    return foldType_;
  }

  public static final int ANCHOR_FOLD_TYPE_FIELD_NUMBER = 10;
  private long anchorFoldType_ = 0L;
  /**
   * <code>uint64 anchor_fold_type = 10;</code>
   * @return The anchorFoldType.
   */
  @java.lang.Override
  public long getAnchorFoldType() {
    return anchorFoldType_;
  }

  public static final int PRIORITYSCORE_FIELD_NUMBER = 11;
  private long priorityScore_ = 0L;
  /**
   * <code>uint64 priorityScore = 11;</code>
   * @return The priorityScore.
   */
  @java.lang.Override
  public long getPriorityScore() {
    return priorityScore_;
  }

  public static final int LOGID_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object logId_ = "";
  /**
   * <code>string logId = 12;</code>
   * @return The logId.
   */
  @java.lang.Override
  public java.lang.String getLogId() {
    java.lang.Object ref = logId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logId_ = s;
      return s;
    }
  }
  /**
   * <code>string logId = 12;</code>
   * @return The bytes for logId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogIdBytes() {
    java.lang.Object ref = logId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGPROCESSFILTERK_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgProcessFilterK_ = "";
  /**
   * <code>string msgProcessFilterK = 13;</code>
   * @return The msgProcessFilterK.
   */
  @java.lang.Override
  public java.lang.String getMsgProcessFilterK() {
    java.lang.Object ref = msgProcessFilterK_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgProcessFilterK_ = s;
      return s;
    }
  }
  /**
   * <code>string msgProcessFilterK = 13;</code>
   * @return The bytes for msgProcessFilterK.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgProcessFilterKBytes() {
    java.lang.Object ref = msgProcessFilterK_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgProcessFilterK_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGPROCESSFILTERV_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgProcessFilterV_ = "";
  /**
   * <code>string msgProcessFilterV = 14;</code>
   * @return The msgProcessFilterV.
   */
  @java.lang.Override
  public java.lang.String getMsgProcessFilterV() {
    java.lang.Object ref = msgProcessFilterV_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgProcessFilterV_ = s;
      return s;
    }
  }
  /**
   * <code>string msgProcessFilterV = 14;</code>
   * @return The bytes for msgProcessFilterV.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgProcessFilterVBytes() {
    java.lang.Object ref = msgProcessFilterV_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgProcessFilterV_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 21;
  private long channelId_ = 0L;
  /**
   * <pre>
   * User user = 15;
   *  Room room = 16;
   * uint64 anchor_fold_type_v2 = 17;
   *  uint64 process_at_sei_time_ms = 18;
   *  uint64 random_dispatch_ms = 19;
   *  bool is_dispatch = 20;
   * </pre>
   *
   * <code>uint64 channel_id = 21;</code>
   * @return The channelId.
   */
  @java.lang.Override
  public long getChannelId() {
    return channelId_;
  }

  public static final int DIFF_SEI2ABS_SECOND_FIELD_NUMBER = 22;
  private long diffSei2AbsSecond_ = 0L;
  /**
   * <code>uint64 diff_sei2abs_second = 22;</code>
   * @return The diffSei2absSecond.
   */
  @java.lang.Override
  public long getDiffSei2AbsSecond() {
    return diffSei2AbsSecond_;
  }

  public static final int ANCHOR_FOLD_DURATION_FIELD_NUMBER = 23;
  private long anchorFoldDuration_ = 0L;
  /**
   * <code>uint64 anchor_fold_duration = 23;</code>
   * @return The anchorFoldDuration.
   */
  @java.lang.Override
  public long getAnchorFoldDuration() {
    return anchorFoldDuration_;
  }

  public static final int APP_ID_FIELD_NUMBER = 24;
  private long appId_ = 0L;
  /**
   * <code>uint64 app_id = 24;</code>
   * @return The appId.
   */
  @java.lang.Override
  public long getAppId() {
    return appId_;
  }

  public static final int TIMESTAMP_MS_FIELD_NUMBER = 25;
  private long timestampMs_ = 0L;
  /**
   * <code>uint64 timestamp_ms = 25;</code>
   * @return The timestampMs.
   */
  @java.lang.Override
  public long getTimestampMs() {
    return timestampMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, method_);
    }
    if (msgId_ != 0L) {
      output.writeUInt64(2, msgId_);
    }
    if (roomId_ != 0L) {
      output.writeUInt64(3, roomId_);
    }
    if (createTime_ != 0L) {
      output.writeUInt64(4, createTime_);
    }
    if (monitor_ != 0) {
      output.writeUInt32(5, monitor_);
    }
    if (isShowMsg_ != false) {
      output.writeBool(6, isShowMsg_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(describe_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, describe_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(8, getDisplayText());
    }
    if (foldType_ != 0L) {
      output.writeUInt64(9, foldType_);
    }
    if (anchorFoldType_ != 0L) {
      output.writeUInt64(10, anchorFoldType_);
    }
    if (priorityScore_ != 0L) {
      output.writeUInt64(11, priorityScore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, logId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgProcessFilterK_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, msgProcessFilterK_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgProcessFilterV_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, msgProcessFilterV_);
    }
    if (channelId_ != 0L) {
      output.writeUInt64(21, channelId_);
    }
    if (diffSei2AbsSecond_ != 0L) {
      output.writeUInt64(22, diffSei2AbsSecond_);
    }
    if (anchorFoldDuration_ != 0L) {
      output.writeUInt64(23, anchorFoldDuration_);
    }
    if (appId_ != 0L) {
      output.writeUInt64(24, appId_);
    }
    if (timestampMs_ != 0L) {
      output.writeUInt64(25, timestampMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, method_);
    }
    if (msgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, msgId_);
    }
    if (roomId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, roomId_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, createTime_);
    }
    if (monitor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, monitor_);
    }
    if (isShowMsg_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isShowMsg_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(describe_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, describe_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getDisplayText());
    }
    if (foldType_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, foldType_);
    }
    if (anchorFoldType_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, anchorFoldType_);
    }
    if (priorityScore_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(11, priorityScore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, logId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgProcessFilterK_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, msgProcessFilterK_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgProcessFilterV_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, msgProcessFilterV_);
    }
    if (channelId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(21, channelId_);
    }
    if (diffSei2AbsSecond_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(22, diffSei2AbsSecond_);
    }
    if (anchorFoldDuration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(23, anchorFoldDuration_);
    }
    if (appId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(24, appId_);
    }
    if (timestampMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(25, timestampMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common)) {
      return super.equals(obj);
    }
    tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common other = (tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common) obj;

    if (!getMethod()
        .equals(other.getMethod())) return false;
    if (getMsgId()
        != other.getMsgId()) return false;
    if (getRoomId()
        != other.getRoomId()) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (getMonitor()
        != other.getMonitor()) return false;
    if (getIsShowMsg()
        != other.getIsShowMsg()) return false;
    if (!getDescribe()
        .equals(other.getDescribe())) return false;
    if (hasDisplayText() != other.hasDisplayText()) return false;
    if (hasDisplayText()) {
      if (!getDisplayText()
          .equals(other.getDisplayText())) return false;
    }
    if (getFoldType()
        != other.getFoldType()) return false;
    if (getAnchorFoldType()
        != other.getAnchorFoldType()) return false;
    if (getPriorityScore()
        != other.getPriorityScore()) return false;
    if (!getLogId()
        .equals(other.getLogId())) return false;
    if (!getMsgProcessFilterK()
        .equals(other.getMsgProcessFilterK())) return false;
    if (!getMsgProcessFilterV()
        .equals(other.getMsgProcessFilterV())) return false;
    if (getChannelId()
        != other.getChannelId()) return false;
    if (getDiffSei2AbsSecond()
        != other.getDiffSei2AbsSecond()) return false;
    if (getAnchorFoldDuration()
        != other.getAnchorFoldDuration()) return false;
    if (getAppId()
        != other.getAppId()) return false;
    if (getTimestampMs()
        != other.getTimestampMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgId());
    hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoomId());
    hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + MONITOR_FIELD_NUMBER;
    hash = (53 * hash) + getMonitor();
    hash = (37 * hash) + IS_SHOW_MSG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsShowMsg());
    hash = (37 * hash) + DESCRIBE_FIELD_NUMBER;
    hash = (53 * hash) + getDescribe().hashCode();
    if (hasDisplayText()) {
      hash = (37 * hash) + DISPLAY_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getDisplayText().hashCode();
    }
    hash = (37 * hash) + FOLD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFoldType());
    hash = (37 * hash) + ANCHOR_FOLD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAnchorFoldType());
    hash = (37 * hash) + PRIORITYSCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPriorityScore());
    hash = (37 * hash) + LOGID_FIELD_NUMBER;
    hash = (53 * hash) + getLogId().hashCode();
    hash = (37 * hash) + MSGPROCESSFILTERK_FIELD_NUMBER;
    hash = (53 * hash) + getMsgProcessFilterK().hashCode();
    hash = (37 * hash) + MSGPROCESSFILTERV_FIELD_NUMBER;
    hash = (53 * hash) + getMsgProcessFilterV().hashCode();
    hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChannelId());
    hash = (37 * hash) + DIFF_SEI2ABS_SECOND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDiffSei2AbsSecond());
    hash = (37 * hash) + ANCHOR_FOLD_DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAnchorFoldDuration());
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAppId());
    hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Common}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Common)
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_Common_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_Common_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.class, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.Builder.class);
    }

    // Construct using tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDisplayTextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      method_ = "";
      msgId_ = 0L;
      roomId_ = 0L;
      createTime_ = 0L;
      monitor_ = 0;
      isShowMsg_ = false;
      describe_ = "";
      displayText_ = null;
      if (displayTextBuilder_ != null) {
        displayTextBuilder_.dispose();
        displayTextBuilder_ = null;
      }
      foldType_ = 0L;
      anchorFoldType_ = 0L;
      priorityScore_ = 0L;
      logId_ = "";
      msgProcessFilterK_ = "";
      msgProcessFilterV_ = "";
      channelId_ = 0L;
      diffSei2AbsSecond_ = 0L;
      anchorFoldDuration_ = 0L;
      appId_ = 0L;
      timestampMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_Common_descriptor;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getDefaultInstanceForType() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.getDefaultInstance();
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common build() {
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common buildPartial() {
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common result = new tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.method_ = method_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msgId_ = msgId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.roomId_ = roomId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.createTime_ = createTime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.monitor_ = monitor_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.isShowMsg_ = isShowMsg_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.describe_ = describe_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.displayText_ = displayTextBuilder_ == null
            ? displayText_
            : displayTextBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.foldType_ = foldType_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.anchorFoldType_ = anchorFoldType_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.priorityScore_ = priorityScore_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.logId_ = logId_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.msgProcessFilterK_ = msgProcessFilterK_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.msgProcessFilterV_ = msgProcessFilterV_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.channelId_ = channelId_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.diffSei2AbsSecond_ = diffSei2AbsSecond_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.anchorFoldDuration_ = anchorFoldDuration_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.appId_ = appId_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.timestampMs_ = timestampMs_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common) {
        return mergeFrom((tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common other) {
      if (other == tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.getDefaultInstance()) return this;
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getMsgId() != 0L) {
        setMsgId(other.getMsgId());
      }
      if (other.getRoomId() != 0L) {
        setRoomId(other.getRoomId());
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getMonitor() != 0) {
        setMonitor(other.getMonitor());
      }
      if (other.getIsShowMsg() != false) {
        setIsShowMsg(other.getIsShowMsg());
      }
      if (!other.getDescribe().isEmpty()) {
        describe_ = other.describe_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.hasDisplayText()) {
        mergeDisplayText(other.getDisplayText());
      }
      if (other.getFoldType() != 0L) {
        setFoldType(other.getFoldType());
      }
      if (other.getAnchorFoldType() != 0L) {
        setAnchorFoldType(other.getAnchorFoldType());
      }
      if (other.getPriorityScore() != 0L) {
        setPriorityScore(other.getPriorityScore());
      }
      if (!other.getLogId().isEmpty()) {
        logId_ = other.logId_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getMsgProcessFilterK().isEmpty()) {
        msgProcessFilterK_ = other.msgProcessFilterK_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getMsgProcessFilterV().isEmpty()) {
        msgProcessFilterV_ = other.msgProcessFilterV_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (other.getChannelId() != 0L) {
        setChannelId(other.getChannelId());
      }
      if (other.getDiffSei2AbsSecond() != 0L) {
        setDiffSei2AbsSecond(other.getDiffSei2AbsSecond());
      }
      if (other.getAnchorFoldDuration() != 0L) {
        setAnchorFoldDuration(other.getAnchorFoldDuration());
      }
      if (other.getAppId() != 0L) {
        setAppId(other.getAppId());
      }
      if (other.getTimestampMs() != 0L) {
        setTimestampMs(other.getTimestampMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              method_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              msgId_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              roomId_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              createTime_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              monitor_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              isShowMsg_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              describe_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getDisplayTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              foldType_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              anchorFoldType_ = input.readUInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              priorityScore_ = input.readUInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              logId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              msgProcessFilterK_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              msgProcessFilterV_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 168: {
              channelId_ = input.readUInt64();
              bitField0_ |= 0x00004000;
              break;
            } // case 168
            case 176: {
              diffSei2AbsSecond_ = input.readUInt64();
              bitField0_ |= 0x00008000;
              break;
            } // case 176
            case 184: {
              anchorFoldDuration_ = input.readUInt64();
              bitField0_ |= 0x00010000;
              break;
            } // case 184
            case 192: {
              appId_ = input.readUInt64();
              bitField0_ |= 0x00020000;
              break;
            } // case 192
            case 200: {
              timestampMs_ = input.readUInt64();
              bitField0_ |= 0x00040000;
              break;
            } // case 200
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object method_ = "";
    /**
     * <code>string method = 1;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method = 1;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 1;</code>
     * @param value The method to set.
     * @return This builder for chaining.
     */
    public Builder setMethod(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      method_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethod() {
      method_ = getDefaultInstance().getMethod();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string method = 1;</code>
     * @param value The bytes for method to set.
     * @return This builder for chaining.
     */
    public Builder setMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      method_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long msgId_ ;
    /**
     * <code>uint64 msg_id = 2;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }
    /**
     * <code>uint64 msg_id = 2;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(long value) {

      msgId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 msg_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgId_ = 0L;
      onChanged();
      return this;
    }

    private long roomId_ ;
    /**
     * <code>uint64 room_id = 3;</code>
     * @return The roomId.
     */
    @java.lang.Override
    public long getRoomId() {
      return roomId_;
    }
    /**
     * <code>uint64 room_id = 3;</code>
     * @param value The roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomId(long value) {

      roomId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 room_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      roomId_ = 0L;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <code>uint64 create_time = 4;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <code>uint64 create_time = 4;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {

      createTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 create_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private int monitor_ ;
    /**
     * <code>uint32 monitor = 5;</code>
     * @return The monitor.
     */
    @java.lang.Override
    public int getMonitor() {
      return monitor_;
    }
    /**
     * <code>uint32 monitor = 5;</code>
     * @param value The monitor to set.
     * @return This builder for chaining.
     */
    public Builder setMonitor(int value) {

      monitor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 monitor = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonitor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      monitor_ = 0;
      onChanged();
      return this;
    }

    private boolean isShowMsg_ ;
    /**
     * <code>bool is_show_msg = 6;</code>
     * @return The isShowMsg.
     */
    @java.lang.Override
    public boolean getIsShowMsg() {
      return isShowMsg_;
    }
    /**
     * <code>bool is_show_msg = 6;</code>
     * @param value The isShowMsg to set.
     * @return This builder for chaining.
     */
    public Builder setIsShowMsg(boolean value) {

      isShowMsg_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_show_msg = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsShowMsg() {
      bitField0_ = (bitField0_ & ~0x00000020);
      isShowMsg_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object describe_ = "";
    /**
     * <code>string describe = 7;</code>
     * @return The describe.
     */
    public java.lang.String getDescribe() {
      java.lang.Object ref = describe_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        describe_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string describe = 7;</code>
     * @return The bytes for describe.
     */
    public com.google.protobuf.ByteString
        getDescribeBytes() {
      java.lang.Object ref = describe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        describe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string describe = 7;</code>
     * @param value The describe to set.
     * @return This builder for chaining.
     */
    public Builder setDescribe(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      describe_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string describe = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescribe() {
      describe_ = getDefaultInstance().getDescribe();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string describe = 7;</code>
     * @param value The bytes for describe to set.
     * @return This builder for chaining.
     */
    public Builder setDescribeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      describe_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text displayText_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder> displayTextBuilder_;
    /**
     * <code>.Text display_text = 8;</code>
     * @return Whether the displayText field is set.
     */
    public boolean hasDisplayText() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.Text display_text = 8;</code>
     * @return The displayText.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getDisplayText() {
      if (displayTextBuilder_ == null) {
        return displayText_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : displayText_;
      } else {
        return displayTextBuilder_.getMessage();
      }
    }
    /**
     * <code>.Text display_text = 8;</code>
     */
    public Builder setDisplayText(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text value) {
      if (displayTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        displayText_ = value;
      } else {
        displayTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.Text display_text = 8;</code>
     */
    public Builder setDisplayText(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder builderForValue) {
      if (displayTextBuilder_ == null) {
        displayText_ = builderForValue.build();
      } else {
        displayTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.Text display_text = 8;</code>
     */
    public Builder mergeDisplayText(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text value) {
      if (displayTextBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          displayText_ != null &&
          displayText_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance()) {
          getDisplayTextBuilder().mergeFrom(value);
        } else {
          displayText_ = value;
        }
      } else {
        displayTextBuilder_.mergeFrom(value);
      }
      if (displayText_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Text display_text = 8;</code>
     */
    public Builder clearDisplayText() {
      bitField0_ = (bitField0_ & ~0x00000080);
      displayText_ = null;
      if (displayTextBuilder_ != null) {
        displayTextBuilder_.dispose();
        displayTextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Text display_text = 8;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder getDisplayTextBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getDisplayTextFieldBuilder().getBuilder();
    }
    /**
     * <code>.Text display_text = 8;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getDisplayTextOrBuilder() {
      if (displayTextBuilder_ != null) {
        return displayTextBuilder_.getMessageOrBuilder();
      } else {
        return displayText_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : displayText_;
      }
    }
    /**
     * <code>.Text display_text = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder> 
        getDisplayTextFieldBuilder() {
      if (displayTextBuilder_ == null) {
        displayTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder>(
                getDisplayText(),
                getParentForChildren(),
                isClean());
        displayText_ = null;
      }
      return displayTextBuilder_;
    }

    private long foldType_ ;
    /**
     * <pre>
     *  DisplayText displayText = 8;
     * </pre>
     *
     * <code>uint64 fold_type = 9;</code>
     * @return The foldType.
     */
    @java.lang.Override
    public long getFoldType() {
      return foldType_;
    }
    /**
     * <pre>
     *  DisplayText displayText = 8;
     * </pre>
     *
     * <code>uint64 fold_type = 9;</code>
     * @param value The foldType to set.
     * @return This builder for chaining.
     */
    public Builder setFoldType(long value) {

      foldType_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  DisplayText displayText = 8;
     * </pre>
     *
     * <code>uint64 fold_type = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoldType() {
      bitField0_ = (bitField0_ & ~0x00000100);
      foldType_ = 0L;
      onChanged();
      return this;
    }

    private long anchorFoldType_ ;
    /**
     * <code>uint64 anchor_fold_type = 10;</code>
     * @return The anchorFoldType.
     */
    @java.lang.Override
    public long getAnchorFoldType() {
      return anchorFoldType_;
    }
    /**
     * <code>uint64 anchor_fold_type = 10;</code>
     * @param value The anchorFoldType to set.
     * @return This builder for chaining.
     */
    public Builder setAnchorFoldType(long value) {

      anchorFoldType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 anchor_fold_type = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnchorFoldType() {
      bitField0_ = (bitField0_ & ~0x00000200);
      anchorFoldType_ = 0L;
      onChanged();
      return this;
    }

    private long priorityScore_ ;
    /**
     * <code>uint64 priorityScore = 11;</code>
     * @return The priorityScore.
     */
    @java.lang.Override
    public long getPriorityScore() {
      return priorityScore_;
    }
    /**
     * <code>uint64 priorityScore = 11;</code>
     * @param value The priorityScore to set.
     * @return This builder for chaining.
     */
    public Builder setPriorityScore(long value) {

      priorityScore_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 priorityScore = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriorityScore() {
      bitField0_ = (bitField0_ & ~0x00000400);
      priorityScore_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object logId_ = "";
    /**
     * <code>string logId = 12;</code>
     * @return The logId.
     */
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string logId = 12;</code>
     * @return The bytes for logId.
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string logId = 12;</code>
     * @param value The logId to set.
     * @return This builder for chaining.
     */
    public Builder setLogId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      logId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string logId = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogId() {
      logId_ = getDefaultInstance().getLogId();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string logId = 12;</code>
     * @param value The bytes for logId to set.
     * @return This builder for chaining.
     */
    public Builder setLogIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      logId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object msgProcessFilterK_ = "";
    /**
     * <code>string msgProcessFilterK = 13;</code>
     * @return The msgProcessFilterK.
     */
    public java.lang.String getMsgProcessFilterK() {
      java.lang.Object ref = msgProcessFilterK_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgProcessFilterK_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgProcessFilterK = 13;</code>
     * @return The bytes for msgProcessFilterK.
     */
    public com.google.protobuf.ByteString
        getMsgProcessFilterKBytes() {
      java.lang.Object ref = msgProcessFilterK_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgProcessFilterK_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgProcessFilterK = 13;</code>
     * @param value The msgProcessFilterK to set.
     * @return This builder for chaining.
     */
    public Builder setMsgProcessFilterK(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgProcessFilterK_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string msgProcessFilterK = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgProcessFilterK() {
      msgProcessFilterK_ = getDefaultInstance().getMsgProcessFilterK();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string msgProcessFilterK = 13;</code>
     * @param value The bytes for msgProcessFilterK to set.
     * @return This builder for chaining.
     */
    public Builder setMsgProcessFilterKBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgProcessFilterK_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object msgProcessFilterV_ = "";
    /**
     * <code>string msgProcessFilterV = 14;</code>
     * @return The msgProcessFilterV.
     */
    public java.lang.String getMsgProcessFilterV() {
      java.lang.Object ref = msgProcessFilterV_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgProcessFilterV_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgProcessFilterV = 14;</code>
     * @return The bytes for msgProcessFilterV.
     */
    public com.google.protobuf.ByteString
        getMsgProcessFilterVBytes() {
      java.lang.Object ref = msgProcessFilterV_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgProcessFilterV_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgProcessFilterV = 14;</code>
     * @param value The msgProcessFilterV to set.
     * @return This builder for chaining.
     */
    public Builder setMsgProcessFilterV(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgProcessFilterV_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>string msgProcessFilterV = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgProcessFilterV() {
      msgProcessFilterV_ = getDefaultInstance().getMsgProcessFilterV();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <code>string msgProcessFilterV = 14;</code>
     * @param value The bytes for msgProcessFilterV to set.
     * @return This builder for chaining.
     */
    public Builder setMsgProcessFilterVBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgProcessFilterV_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private long channelId_ ;
    /**
     * <pre>
     * User user = 15;
     *  Room room = 16;
     * uint64 anchor_fold_type_v2 = 17;
     *  uint64 process_at_sei_time_ms = 18;
     *  uint64 random_dispatch_ms = 19;
     *  bool is_dispatch = 20;
     * </pre>
     *
     * <code>uint64 channel_id = 21;</code>
     * @return The channelId.
     */
    @java.lang.Override
    public long getChannelId() {
      return channelId_;
    }
    /**
     * <pre>
     * User user = 15;
     *  Room room = 16;
     * uint64 anchor_fold_type_v2 = 17;
     *  uint64 process_at_sei_time_ms = 18;
     *  uint64 random_dispatch_ms = 19;
     *  bool is_dispatch = 20;
     * </pre>
     *
     * <code>uint64 channel_id = 21;</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(long value) {

      channelId_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User user = 15;
     *  Room room = 16;
     * uint64 anchor_fold_type_v2 = 17;
     *  uint64 process_at_sei_time_ms = 18;
     *  uint64 random_dispatch_ms = 19;
     *  bool is_dispatch = 20;
     * </pre>
     *
     * <code>uint64 channel_id = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      bitField0_ = (bitField0_ & ~0x00004000);
      channelId_ = 0L;
      onChanged();
      return this;
    }

    private long diffSei2AbsSecond_ ;
    /**
     * <code>uint64 diff_sei2abs_second = 22;</code>
     * @return The diffSei2absSecond.
     */
    @java.lang.Override
    public long getDiffSei2AbsSecond() {
      return diffSei2AbsSecond_;
    }
    /**
     * <code>uint64 diff_sei2abs_second = 22;</code>
     * @param value The diffSei2absSecond to set.
     * @return This builder for chaining.
     */
    public Builder setDiffSei2AbsSecond(long value) {

      diffSei2AbsSecond_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 diff_sei2abs_second = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiffSei2AbsSecond() {
      bitField0_ = (bitField0_ & ~0x00008000);
      diffSei2AbsSecond_ = 0L;
      onChanged();
      return this;
    }

    private long anchorFoldDuration_ ;
    /**
     * <code>uint64 anchor_fold_duration = 23;</code>
     * @return The anchorFoldDuration.
     */
    @java.lang.Override
    public long getAnchorFoldDuration() {
      return anchorFoldDuration_;
    }
    /**
     * <code>uint64 anchor_fold_duration = 23;</code>
     * @param value The anchorFoldDuration to set.
     * @return This builder for chaining.
     */
    public Builder setAnchorFoldDuration(long value) {

      anchorFoldDuration_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 anchor_fold_duration = 23;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnchorFoldDuration() {
      bitField0_ = (bitField0_ & ~0x00010000);
      anchorFoldDuration_ = 0L;
      onChanged();
      return this;
    }

    private long appId_ ;
    /**
     * <code>uint64 app_id = 24;</code>
     * @return The appId.
     */
    @java.lang.Override
    public long getAppId() {
      return appId_;
    }
    /**
     * <code>uint64 app_id = 24;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(long value) {

      appId_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 app_id = 24;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      bitField0_ = (bitField0_ & ~0x00020000);
      appId_ = 0L;
      onChanged();
      return this;
    }

    private long timestampMs_ ;
    /**
     * <code>uint64 timestamp_ms = 25;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public long getTimestampMs() {
      return timestampMs_;
    }
    /**
     * <code>uint64 timestamp_ms = 25;</code>
     * @param value The timestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMs(long value) {

      timestampMs_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp_ms = 25;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00040000);
      timestampMs_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Common)
  }

  // @@protoc_insertion_point(class_scope:Common)
  private static final tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common();
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Common>
      PARSER = new com.google.protobuf.AbstractParser<Common>() {
    @java.lang.Override
    public Common parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Common> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Common> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

