// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

public interface CommonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Common)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string method = 1;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 1;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>uint64 msg_id = 2;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>uint64 room_id = 3;</code>
   * @return The roomId.
   */
  long getRoomId();

  /**
   * <code>uint64 create_time = 4;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <code>uint32 monitor = 5;</code>
   * @return The monitor.
   */
  int getMonitor();

  /**
   * <code>bool is_show_msg = 6;</code>
   * @return The isShowMsg.
   */
  boolean getIsShowMsg();

  /**
   * <code>string describe = 7;</code>
   * @return The describe.
   */
  java.lang.String getDescribe();
  /**
   * <code>string describe = 7;</code>
   * @return The bytes for describe.
   */
  com.google.protobuf.ByteString
      getDescribeBytes();

  /**
   * <code>.Text display_text = 8;</code>
   * @return Whether the displayText field is set.
   */
  boolean hasDisplayText();
  /**
   * <code>.Text display_text = 8;</code>
   * @return The displayText.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getDisplayText();
  /**
   * <code>.Text display_text = 8;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getDisplayTextOrBuilder();

  /**
   * <pre>
   *  DisplayText displayText = 8;
   * </pre>
   *
   * <code>uint64 fold_type = 9;</code>
   * @return The foldType.
   */
  long getFoldType();

  /**
   * <code>uint64 anchor_fold_type = 10;</code>
   * @return The anchorFoldType.
   */
  long getAnchorFoldType();

  /**
   * <code>uint64 priorityScore = 11;</code>
   * @return The priorityScore.
   */
  long getPriorityScore();

  /**
   * <code>string logId = 12;</code>
   * @return The logId.
   */
  java.lang.String getLogId();
  /**
   * <code>string logId = 12;</code>
   * @return The bytes for logId.
   */
  com.google.protobuf.ByteString
      getLogIdBytes();

  /**
   * <code>string msgProcessFilterK = 13;</code>
   * @return The msgProcessFilterK.
   */
  java.lang.String getMsgProcessFilterK();
  /**
   * <code>string msgProcessFilterK = 13;</code>
   * @return The bytes for msgProcessFilterK.
   */
  com.google.protobuf.ByteString
      getMsgProcessFilterKBytes();

  /**
   * <code>string msgProcessFilterV = 14;</code>
   * @return The msgProcessFilterV.
   */
  java.lang.String getMsgProcessFilterV();
  /**
   * <code>string msgProcessFilterV = 14;</code>
   * @return The bytes for msgProcessFilterV.
   */
  com.google.protobuf.ByteString
      getMsgProcessFilterVBytes();

  /**
   * <pre>
   * User user = 15;
   *  Room room = 16;
   * uint64 anchor_fold_type_v2 = 17;
   *  uint64 process_at_sei_time_ms = 18;
   *  uint64 random_dispatch_ms = 19;
   *  bool is_dispatch = 20;
   * </pre>
   *
   * <code>uint64 channel_id = 21;</code>
   * @return The channelId.
   */
  long getChannelId();

  /**
   * <code>uint64 diff_sei2abs_second = 22;</code>
   * @return The diffSei2absSecond.
   */
  long getDiffSei2AbsSecond();

  /**
   * <code>uint64 anchor_fold_duration = 23;</code>
   * @return The anchorFoldDuration.
   */
  long getAnchorFoldDuration();

  /**
   * <code>uint64 app_id = 24;</code>
   * @return The appId.
   */
  long getAppId();

  /**
   * <code>uint64 timestamp_ms = 25;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
