// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

public interface EmojiChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmojiChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 2;</code>
   * @return The user.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getUser();
  /**
   * <code>.User user = 2;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>uint64 emojiId = 3;</code>
   * @return The emojiId.
   */
  long getEmojiId();

  /**
   * <code>.Text emojiContent = 4;</code>
   * @return Whether the emojiContent field is set.
   */
  boolean hasEmojiContent();
  /**
   * <code>.Text emojiContent = 4;</code>
   * @return The emojiContent.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getEmojiContent();
  /**
   * <code>.Text emojiContent = 4;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getEmojiContentOrBuilder();

  /**
   * <code>string defaultContent = 5;</code>
   * @return The defaultContent.
   */
  java.lang.String getDefaultContent();
  /**
   * <code>string defaultContent = 5;</code>
   * @return The bytes for defaultContent.
   */
  com.google.protobuf.ByteString
      getDefaultContentBytes();

  /**
   * <code>.Image backgroundImage = 6;</code>
   * @return Whether the backgroundImage field is set.
   */
  boolean hasBackgroundImage();
  /**
   * <code>.Image backgroundImage = 6;</code>
   * @return The backgroundImage.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getBackgroundImage();
  /**
   * <code>.Image backgroundImage = 6;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getBackgroundImageOrBuilder();

  /**
   * <code>bool fromIntercom = 7;</code>
   * @return The fromIntercom.
   */
  boolean getFromIntercom();

  /**
   * <code>bool intercomHideUserCard = 8;</code>
   * @return The intercomHideUserCard.
   */
  boolean getIntercomHideUserCard();

  /**
   * <code>.PublicAreaCommon public_area_common = 9;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  boolean hasPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon public_area_common = 9;</code>
   * @return The publicAreaCommon.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.PublicAreaCommon getPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon public_area_common = 9;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder();
}
