// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

/**
 * Protobuf type {@code GiftStruct}
 */
public final class GiftStruct extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GiftStruct)
    GiftStructOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GiftStruct.newBuilder() to construct.
  private GiftStruct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GiftStruct() {
    describe_ = "";
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GiftStruct();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftStruct_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftStruct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.class, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.Builder.class);
  }

  private int bitField0_;
  public static final int IMAGE_FIELD_NUMBER = 1;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image image_;
  /**
   * <code>.Image image = 1;</code>
   * @return Whether the image field is set.
   */
  @java.lang.Override
  public boolean hasImage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Image image = 1;</code>
   * @return The image.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getImage() {
    return image_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : image_;
  }
  /**
   * <code>.Image image = 1;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getImageOrBuilder() {
    return image_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : image_;
  }

  public static final int DESCRIBE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object describe_ = "";
  /**
   * <code>string describe = 2;</code>
   * @return The describe.
   */
  @java.lang.Override
  public java.lang.String getDescribe() {
    java.lang.Object ref = describe_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      describe_ = s;
      return s;
    }
  }
  /**
   * <code>string describe = 2;</code>
   * @return The bytes for describe.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescribeBytes() {
    java.lang.Object ref = describe_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      describe_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_FIELD_NUMBER = 4;
  private long duration_ = 0L;
  /**
   * <pre>
   *  bool notify = 3;
   * </pre>
   *
   * <code>uint64 duration = 4;</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }

  public static final int ID_FIELD_NUMBER = 5;
  private long id_ = 0L;
  /**
   * <code>uint64 id = 5;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int FORLINKMIC_FIELD_NUMBER = 7;
  private boolean forLinkmic_ = false;
  /**
   * <pre>
   *  //  GiftStructFansClubInfo fansclubInfo = 6;
   * </pre>
   *
   * <code>bool forLinkmic = 7;</code>
   * @return The forLinkmic.
   */
  @java.lang.Override
  public boolean getForLinkmic() {
    return forLinkmic_;
  }

  public static final int COMBO_FIELD_NUMBER = 10;
  private boolean combo_ = false;
  /**
   * <pre>
   *  bool doodle = 8;
   *  bool forFansclub = 9;
   * </pre>
   *
   * <code>bool combo = 10;</code>
   * @return The combo.
   */
  @java.lang.Override
  public boolean getCombo() {
    return combo_;
  }

  public static final int TYPE_FIELD_NUMBER = 11;
  private int type_ = 0;
  /**
   * <code>uint32 type = 11;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int DIAMONDCOUNT_FIELD_NUMBER = 12;
  private int diamondCount_ = 0;
  /**
   * <code>uint32 diamondCount = 12;</code>
   * @return The diamondCount.
   */
  @java.lang.Override
  public int getDiamondCount() {
    return diamondCount_;
  }

  public static final int ISDISPLAYEDONPANEL_FIELD_NUMBER = 13;
  private boolean isDisplayedOnPanel_ = false;
  /**
   * <code>bool isDisplayedOnPanel = 13;</code>
   * @return The isDisplayedOnPanel.
   */
  @java.lang.Override
  public boolean getIsDisplayedOnPanel() {
    return isDisplayedOnPanel_;
  }

  public static final int NAME_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   *  uint64 primaryEffectId = 14;
   *  Image giftLabelIcon = 15;
   * </pre>
   *
   * <code>string name = 16;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *  uint64 primaryEffectId = 14;
   *  Image giftLabelIcon = 15;
   * </pre>
   *
   * <code>string name = 16;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ICON_FIELD_NUMBER = 21;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image icon_;
  /**
   * <pre>
   *  string region = 17;
   *  string manual = 18;
   *  bool forCustom = 19;
   *  //  specialEffectsMap = 20;
   * </pre>
   *
   * <code>.Image icon = 21;</code>
   * @return Whether the icon field is set.
   */
  @java.lang.Override
  public boolean hasIcon() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   *  string region = 17;
   *  string manual = 18;
   *  bool forCustom = 19;
   *  //  specialEffectsMap = 20;
   * </pre>
   *
   * <code>.Image icon = 21;</code>
   * @return The icon.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getIcon() {
    return icon_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : icon_;
  }
  /**
   * <pre>
   *  string region = 17;
   *  string manual = 18;
   *  bool forCustom = 19;
   *  //  specialEffectsMap = 20;
   * </pre>
   *
   * <code>.Image icon = 21;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getIconOrBuilder() {
    return icon_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : icon_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getImage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(describe_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, describe_);
    }
    if (duration_ != 0L) {
      output.writeUInt64(4, duration_);
    }
    if (id_ != 0L) {
      output.writeUInt64(5, id_);
    }
    if (forLinkmic_ != false) {
      output.writeBool(7, forLinkmic_);
    }
    if (combo_ != false) {
      output.writeBool(10, combo_);
    }
    if (type_ != 0) {
      output.writeUInt32(11, type_);
    }
    if (diamondCount_ != 0) {
      output.writeUInt32(12, diamondCount_);
    }
    if (isDisplayedOnPanel_ != false) {
      output.writeBool(13, isDisplayedOnPanel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(21, getIcon());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(describe_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, describe_);
    }
    if (duration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, duration_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, id_);
    }
    if (forLinkmic_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, forLinkmic_);
    }
    if (combo_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, combo_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(11, type_);
    }
    if (diamondCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(12, diamondCount_);
    }
    if (isDisplayedOnPanel_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, isDisplayedOnPanel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getIcon());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct)) {
      return super.equals(obj);
    }
    tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct other = (tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct) obj;

    if (hasImage() != other.hasImage()) return false;
    if (hasImage()) {
      if (!getImage()
          .equals(other.getImage())) return false;
    }
    if (!getDescribe()
        .equals(other.getDescribe())) return false;
    if (getDuration()
        != other.getDuration()) return false;
    if (getId()
        != other.getId()) return false;
    if (getForLinkmic()
        != other.getForLinkmic()) return false;
    if (getCombo()
        != other.getCombo()) return false;
    if (getType()
        != other.getType()) return false;
    if (getDiamondCount()
        != other.getDiamondCount()) return false;
    if (getIsDisplayedOnPanel()
        != other.getIsDisplayedOnPanel()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasIcon() != other.hasIcon()) return false;
    if (hasIcon()) {
      if (!getIcon()
          .equals(other.getIcon())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasImage()) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
    }
    hash = (37 * hash) + DESCRIBE_FIELD_NUMBER;
    hash = (53 * hash) + getDescribe().hashCode();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDuration());
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + FORLINKMIC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getForLinkmic());
    hash = (37 * hash) + COMBO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCombo());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + DIAMONDCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getDiamondCount();
    hash = (37 * hash) + ISDISPLAYEDONPANEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDisplayedOnPanel());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasIcon()) {
      hash = (37 * hash) + ICON_FIELD_NUMBER;
      hash = (53 * hash) + getIcon().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GiftStruct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GiftStruct)
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStructOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftStruct_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftStruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.class, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.Builder.class);
    }

    // Construct using tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImageFieldBuilder();
        getIconFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      image_ = null;
      if (imageBuilder_ != null) {
        imageBuilder_.dispose();
        imageBuilder_ = null;
      }
      describe_ = "";
      duration_ = 0L;
      id_ = 0L;
      forLinkmic_ = false;
      combo_ = false;
      type_ = 0;
      diamondCount_ = 0;
      isDisplayedOnPanel_ = false;
      name_ = "";
      icon_ = null;
      if (iconBuilder_ != null) {
        iconBuilder_.dispose();
        iconBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftStruct_descriptor;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct getDefaultInstanceForType() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.getDefaultInstance();
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct build() {
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct buildPartial() {
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct result = new tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.image_ = imageBuilder_ == null
            ? image_
            : imageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.describe_ = describe_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.duration_ = duration_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.forLinkmic_ = forLinkmic_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.combo_ = combo_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.diamondCount_ = diamondCount_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.isDisplayedOnPanel_ = isDisplayedOnPanel_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.icon_ = iconBuilder_ == null
            ? icon_
            : iconBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct) {
        return mergeFrom((tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct other) {
      if (other == tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.getDefaultInstance()) return this;
      if (other.hasImage()) {
        mergeImage(other.getImage());
      }
      if (!other.getDescribe().isEmpty()) {
        describe_ = other.describe_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getDuration() != 0L) {
        setDuration(other.getDuration());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getForLinkmic() != false) {
        setForLinkmic(other.getForLinkmic());
      }
      if (other.getCombo() != false) {
        setCombo(other.getCombo());
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getDiamondCount() != 0) {
        setDiamondCount(other.getDiamondCount());
      }
      if (other.getIsDisplayedOnPanel() != false) {
        setIsDisplayedOnPanel(other.getIsDisplayedOnPanel());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.hasIcon()) {
        mergeIcon(other.getIcon());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getImageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              describe_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 32: {
              duration_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 32
            case 40: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 40
            case 56: {
              forLinkmic_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 56
            case 80: {
              combo_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 80
            case 88: {
              type_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 88
            case 96: {
              diamondCount_ = input.readUInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 96
            case 104: {
              isDisplayedOnPanel_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 104
            case 130: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 130
            case 170: {
              input.readMessage(
                  getIconFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 170
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image image_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder> imageBuilder_;
    /**
     * <code>.Image image = 1;</code>
     * @return Whether the image field is set.
     */
    public boolean hasImage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Image image = 1;</code>
     * @return The image.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getImage() {
      if (imageBuilder_ == null) {
        return image_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : image_;
      } else {
        return imageBuilder_.getMessage();
      }
    }
    /**
     * <code>.Image image = 1;</code>
     */
    public Builder setImage(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image_ = value;
      } else {
        imageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Image image = 1;</code>
     */
    public Builder setImage(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        image_ = builderForValue.build();
      } else {
        imageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Image image = 1;</code>
     */
    public Builder mergeImage(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          image_ != null &&
          image_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance()) {
          getImageBuilder().mergeFrom(value);
        } else {
          image_ = value;
        }
      } else {
        imageBuilder_.mergeFrom(value);
      }
      if (image_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Image image = 1;</code>
     */
    public Builder clearImage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      image_ = null;
      if (imageBuilder_ != null) {
        imageBuilder_.dispose();
        imageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Image image = 1;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder getImageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getImageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Image image = 1;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getImageOrBuilder() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilder();
      } else {
        return image_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : image_;
      }
    }
    /**
     * <code>.Image image = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder>(
                getImage(),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }

    private java.lang.Object describe_ = "";
    /**
     * <code>string describe = 2;</code>
     * @return The describe.
     */
    public java.lang.String getDescribe() {
      java.lang.Object ref = describe_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        describe_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string describe = 2;</code>
     * @return The bytes for describe.
     */
    public com.google.protobuf.ByteString
        getDescribeBytes() {
      java.lang.Object ref = describe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        describe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string describe = 2;</code>
     * @param value The describe to set.
     * @return This builder for chaining.
     */
    public Builder setDescribe(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      describe_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string describe = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescribe() {
      describe_ = getDefaultInstance().getDescribe();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string describe = 2;</code>
     * @param value The bytes for describe to set.
     * @return This builder for chaining.
     */
    public Builder setDescribeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      describe_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long duration_ ;
    /**
     * <pre>
     *  bool notify = 3;
     * </pre>
     *
     * <code>uint64 duration = 4;</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return duration_;
    }
    /**
     * <pre>
     *  bool notify = 3;
     * </pre>
     *
     * <code>uint64 duration = 4;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {

      duration_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  bool notify = 3;
     * </pre>
     *
     * <code>uint64 duration = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000004);
      duration_ = 0L;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>uint64 id = 5;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>uint64 id = 5;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      id_ = 0L;
      onChanged();
      return this;
    }

    private boolean forLinkmic_ ;
    /**
     * <pre>
     *  //  GiftStructFansClubInfo fansclubInfo = 6;
     * </pre>
     *
     * <code>bool forLinkmic = 7;</code>
     * @return The forLinkmic.
     */
    @java.lang.Override
    public boolean getForLinkmic() {
      return forLinkmic_;
    }
    /**
     * <pre>
     *  //  GiftStructFansClubInfo fansclubInfo = 6;
     * </pre>
     *
     * <code>bool forLinkmic = 7;</code>
     * @param value The forLinkmic to set.
     * @return This builder for chaining.
     */
    public Builder setForLinkmic(boolean value) {

      forLinkmic_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  //  GiftStructFansClubInfo fansclubInfo = 6;
     * </pre>
     *
     * <code>bool forLinkmic = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearForLinkmic() {
      bitField0_ = (bitField0_ & ~0x00000010);
      forLinkmic_ = false;
      onChanged();
      return this;
    }

    private boolean combo_ ;
    /**
     * <pre>
     *  bool doodle = 8;
     *  bool forFansclub = 9;
     * </pre>
     *
     * <code>bool combo = 10;</code>
     * @return The combo.
     */
    @java.lang.Override
    public boolean getCombo() {
      return combo_;
    }
    /**
     * <pre>
     *  bool doodle = 8;
     *  bool forFansclub = 9;
     * </pre>
     *
     * <code>bool combo = 10;</code>
     * @param value The combo to set.
     * @return This builder for chaining.
     */
    public Builder setCombo(boolean value) {

      combo_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  bool doodle = 8;
     *  bool forFansclub = 9;
     * </pre>
     *
     * <code>bool combo = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCombo() {
      bitField0_ = (bitField0_ & ~0x00000020);
      combo_ = false;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>uint32 type = 11;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>uint32 type = 11;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {

      type_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 type = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      type_ = 0;
      onChanged();
      return this;
    }

    private int diamondCount_ ;
    /**
     * <code>uint32 diamondCount = 12;</code>
     * @return The diamondCount.
     */
    @java.lang.Override
    public int getDiamondCount() {
      return diamondCount_;
    }
    /**
     * <code>uint32 diamondCount = 12;</code>
     * @param value The diamondCount to set.
     * @return This builder for chaining.
     */
    public Builder setDiamondCount(int value) {

      diamondCount_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 diamondCount = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiamondCount() {
      bitField0_ = (bitField0_ & ~0x00000080);
      diamondCount_ = 0;
      onChanged();
      return this;
    }

    private boolean isDisplayedOnPanel_ ;
    /**
     * <code>bool isDisplayedOnPanel = 13;</code>
     * @return The isDisplayedOnPanel.
     */
    @java.lang.Override
    public boolean getIsDisplayedOnPanel() {
      return isDisplayedOnPanel_;
    }
    /**
     * <code>bool isDisplayedOnPanel = 13;</code>
     * @param value The isDisplayedOnPanel to set.
     * @return This builder for chaining.
     */
    public Builder setIsDisplayedOnPanel(boolean value) {

      isDisplayedOnPanel_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bool isDisplayedOnPanel = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDisplayedOnPanel() {
      bitField0_ = (bitField0_ & ~0x00000100);
      isDisplayedOnPanel_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *  uint64 primaryEffectId = 14;
     *  Image giftLabelIcon = 15;
     * </pre>
     *
     * <code>string name = 16;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *  uint64 primaryEffectId = 14;
     *  Image giftLabelIcon = 15;
     * </pre>
     *
     * <code>string name = 16;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *  uint64 primaryEffectId = 14;
     *  Image giftLabelIcon = 15;
     * </pre>
     *
     * <code>string name = 16;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  uint64 primaryEffectId = 14;
     *  Image giftLabelIcon = 15;
     * </pre>
     *
     * <code>string name = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  uint64 primaryEffectId = 14;
     *  Image giftLabelIcon = 15;
     * </pre>
     *
     * <code>string name = 16;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image icon_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder> iconBuilder_;
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     * @return Whether the icon field is set.
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     * @return The icon.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getIcon() {
      if (iconBuilder_ == null) {
        return icon_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : icon_;
      } else {
        return iconBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     */
    public Builder setIcon(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image value) {
      if (iconBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        icon_ = value;
      } else {
        iconBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     */
    public Builder setIcon(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder builderForValue) {
      if (iconBuilder_ == null) {
        icon_ = builderForValue.build();
      } else {
        iconBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     */
    public Builder mergeIcon(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image value) {
      if (iconBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          icon_ != null &&
          icon_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance()) {
          getIconBuilder().mergeFrom(value);
        } else {
          icon_ = value;
        }
      } else {
        iconBuilder_.mergeFrom(value);
      }
      if (icon_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     */
    public Builder clearIcon() {
      bitField0_ = (bitField0_ & ~0x00000400);
      icon_ = null;
      if (iconBuilder_ != null) {
        iconBuilder_.dispose();
        iconBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder getIconBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getIconFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getIconOrBuilder() {
      if (iconBuilder_ != null) {
        return iconBuilder_.getMessageOrBuilder();
      } else {
        return icon_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.getDefaultInstance() : icon_;
      }
    }
    /**
     * <pre>
     *  string region = 17;
     *  string manual = 18;
     *  bool forCustom = 19;
     *  //  specialEffectsMap = 20;
     * </pre>
     *
     * <code>.Image icon = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder> 
        getIconFieldBuilder() {
      if (iconBuilder_ == null) {
        iconBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder>(
                getIcon(),
                getParentForChildren(),
                isClean());
        icon_ = null;
      }
      return iconBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GiftStruct)
  }

  // @@protoc_insertion_point(class_scope:GiftStruct)
  private static final tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct();
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GiftStruct>
      PARSER = new com.google.protobuf.AbstractParser<GiftStruct>() {
    @java.lang.Override
    public GiftStruct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GiftStruct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GiftStruct> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

