// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

/**
 * <pre>
 * 礼物消息
 * </pre>
 *
 * Protobuf type {@code GiftMessage}
 */
public final class GiftMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GiftMessage)
    GiftMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GiftMessage.newBuilder() to construct.
  private GiftMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GiftMessage() {
    logId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GiftMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage.class, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage.Builder.class);
  }

  private int bitField0_;
  public static final int COMMON_FIELD_NUMBER = 1;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common common_;
  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  @java.lang.Override
  public boolean hasCommon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getCommon() {
    return common_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.getDefaultInstance() : common_;
  }
  /**
   * <code>.Common common = 1;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder getCommonOrBuilder() {
    return common_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.getDefaultInstance() : common_;
  }

  public static final int GIFTID_FIELD_NUMBER = 2;
  private long giftId_ = 0L;
  /**
   * <code>uint64 giftId = 2;</code>
   * @return The giftId.
   */
  @java.lang.Override
  public long getGiftId() {
    return giftId_;
  }

  public static final int FANTICKETCOUNT_FIELD_NUMBER = 3;
  private long fanTicketCount_ = 0L;
  /**
   * <code>uint64 fanTicketCount = 3;</code>
   * @return The fanTicketCount.
   */
  @java.lang.Override
  public long getFanTicketCount() {
    return fanTicketCount_;
  }

  public static final int GROUPCOUNT_FIELD_NUMBER = 4;
  private long groupCount_ = 0L;
  /**
   * <code>uint64 groupCount = 4;</code>
   * @return The groupCount.
   */
  @java.lang.Override
  public long getGroupCount() {
    return groupCount_;
  }

  public static final int REPEATCOUNT_FIELD_NUMBER = 5;
  private long repeatCount_ = 0L;
  /**
   * <code>uint64 repeatCount = 5;</code>
   * @return The repeatCount.
   */
  @java.lang.Override
  public long getRepeatCount() {
    return repeatCount_;
  }

  public static final int COMBOCOUNT_FIELD_NUMBER = 6;
  private long comboCount_ = 0L;
  /**
   * <code>uint64 comboCount = 6;</code>
   * @return The comboCount.
   */
  @java.lang.Override
  public long getComboCount() {
    return comboCount_;
  }

  public static final int USER_FIELD_NUMBER = 7;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User user_;
  /**
   * <code>.User user = 7;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.User user = 7;</code>
   * @return The user.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getUser() {
    return user_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.User user = 7;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getUserOrBuilder() {
    return user_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : user_;
  }

  public static final int TOUSER_FIELD_NUMBER = 8;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User toUser_;
  /**
   * <code>.User toUser = 8;</code>
   * @return Whether the toUser field is set.
   */
  @java.lang.Override
  public boolean hasToUser() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.User toUser = 8;</code>
   * @return The toUser.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getToUser() {
    return toUser_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : toUser_;
  }
  /**
   * <code>.User toUser = 8;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getToUserOrBuilder() {
    return toUser_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : toUser_;
  }

  public static final int REPEATEND_FIELD_NUMBER = 9;
  private int repeatEnd_ = 0;
  /**
   * <code>uint32 repeatEnd = 9;</code>
   * @return The repeatEnd.
   */
  @java.lang.Override
  public int getRepeatEnd() {
    return repeatEnd_;
  }

  public static final int GROUPID_FIELD_NUMBER = 11;
  private long groupId_ = 0L;
  /**
   * <pre>
   *  TextEffect textEffect = 10;
   * </pre>
   *
   * <code>uint64 groupId = 11;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public long getGroupId() {
    return groupId_;
  }

  public static final int ROOMFANTICKETCOUNT_FIELD_NUMBER = 13;
  private long roomFanTicketCount_ = 0L;
  /**
   * <pre>
   *  uint64 incomeTaskgifts = 12;
   * </pre>
   *
   * <code>uint64 roomFanTicketCount = 13;</code>
   * @return The roomFanTicketCount.
   */
  @java.lang.Override
  public long getRoomFanTicketCount() {
    return roomFanTicketCount_;
  }

  public static final int GIFT_FIELD_NUMBER = 15;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct gift_;
  /**
   * <pre>
   *  GiftIMPriority priority = 14;
   * </pre>
   *
   * <code>.GiftStruct gift = 15;</code>
   * @return Whether the gift field is set.
   */
  @java.lang.Override
  public boolean hasGift() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   *  GiftIMPriority priority = 14;
   * </pre>
   *
   * <code>.GiftStruct gift = 15;</code>
   * @return The gift.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct getGift() {
    return gift_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.getDefaultInstance() : gift_;
  }
  /**
   * <pre>
   *  GiftIMPriority priority = 14;
   * </pre>
   *
   * <code>.GiftStruct gift = 15;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStructOrBuilder getGiftOrBuilder() {
    return gift_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.getDefaultInstance() : gift_;
  }

  public static final int LOGID_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private volatile java.lang.Object logId_ = "";
  /**
   * <code>string logId = 16;</code>
   * @return The logId.
   */
  @java.lang.Override
  public java.lang.String getLogId() {
    java.lang.Object ref = logId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logId_ = s;
      return s;
    }
  }
  /**
   * <code>string logId = 16;</code>
   * @return The bytes for logId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogIdBytes() {
    java.lang.Object ref = logId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDTYPE_FIELD_NUMBER = 17;
  private long sendType_ = 0L;
  /**
   * <code>uint64 sendType = 17;</code>
   * @return The sendType.
   */
  @java.lang.Override
  public long getSendType() {
    return sendType_;
  }

  public static final int TRAYDISPLAYTEXT_FIELD_NUMBER = 19;
  private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text trayDisplayText_;
  /**
   * <pre>
   *  PublicAreaCommon publicAreaCommon = 18;
   * </pre>
   *
   * <code>.Text trayDisplayText = 19;</code>
   * @return Whether the trayDisplayText field is set.
   */
  @java.lang.Override
  public boolean hasTrayDisplayText() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   *  PublicAreaCommon publicAreaCommon = 18;
   * </pre>
   *
   * <code>.Text trayDisplayText = 19;</code>
   * @return The trayDisplayText.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getTrayDisplayText() {
    return trayDisplayText_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : trayDisplayText_;
  }
  /**
   * <pre>
   *  PublicAreaCommon publicAreaCommon = 18;
   * </pre>
   *
   * <code>.Text trayDisplayText = 19;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getTrayDisplayTextOrBuilder() {
    return trayDisplayText_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : trayDisplayText_;
  }

  public static final int FORCEDISPLAYEFFECTS_FIELD_NUMBER = 34;
  private long forceDisplayEffects_ = 0L;
  /**
   * <pre>
   *  uint64 bannedDisplayEffects = 20;
   *  //  GiftTrayInfo trayInfo = 21;
   *  //  AssetEffectMixInfo assetEffectMixInfo = 22;
   *  bool displayForSelf = 25;
   *  string interactGiftInfo = 26;
   *  string diyItemInfo = 27;
   *  repeated uint64 minAssetSetList = 28;
   *  uint64 totalCount = 29;
   *  uint32 clientGiftSource = 30;
   *  //  AnchorGiftData anchorGift = 31;
   *  repeated uint64 toUserIdsList = 32;
   *  uint64 sendTime = 33;
   * </pre>
   *
   * <code>uint64 forceDisplayEffects = 34;</code>
   * @return The forceDisplayEffects.
   */
  @java.lang.Override
  public long getForceDisplayEffects() {
    return forceDisplayEffects_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCommon());
    }
    if (giftId_ != 0L) {
      output.writeUInt64(2, giftId_);
    }
    if (fanTicketCount_ != 0L) {
      output.writeUInt64(3, fanTicketCount_);
    }
    if (groupCount_ != 0L) {
      output.writeUInt64(4, groupCount_);
    }
    if (repeatCount_ != 0L) {
      output.writeUInt64(5, repeatCount_);
    }
    if (comboCount_ != 0L) {
      output.writeUInt64(6, comboCount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getUser());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(8, getToUser());
    }
    if (repeatEnd_ != 0) {
      output.writeUInt32(9, repeatEnd_);
    }
    if (groupId_ != 0L) {
      output.writeUInt64(11, groupId_);
    }
    if (roomFanTicketCount_ != 0L) {
      output.writeUInt64(13, roomFanTicketCount_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(15, getGift());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, logId_);
    }
    if (sendType_ != 0L) {
      output.writeUInt64(17, sendType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(19, getTrayDisplayText());
    }
    if (forceDisplayEffects_ != 0L) {
      output.writeUInt64(34, forceDisplayEffects_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommon());
    }
    if (giftId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, giftId_);
    }
    if (fanTicketCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, fanTicketCount_);
    }
    if (groupCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, groupCount_);
    }
    if (repeatCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, repeatCount_);
    }
    if (comboCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, comboCount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getUser());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getToUser());
    }
    if (repeatEnd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, repeatEnd_);
    }
    if (groupId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(11, groupId_);
    }
    if (roomFanTicketCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, roomFanTicketCount_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getGift());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, logId_);
    }
    if (sendType_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(17, sendType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, getTrayDisplayText());
    }
    if (forceDisplayEffects_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(34, forceDisplayEffects_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage)) {
      return super.equals(obj);
    }
    tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage other = (tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage) obj;

    if (hasCommon() != other.hasCommon()) return false;
    if (hasCommon()) {
      if (!getCommon()
          .equals(other.getCommon())) return false;
    }
    if (getGiftId()
        != other.getGiftId()) return false;
    if (getFanTicketCount()
        != other.getFanTicketCount()) return false;
    if (getGroupCount()
        != other.getGroupCount()) return false;
    if (getRepeatCount()
        != other.getRepeatCount()) return false;
    if (getComboCount()
        != other.getComboCount()) return false;
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (hasToUser() != other.hasToUser()) return false;
    if (hasToUser()) {
      if (!getToUser()
          .equals(other.getToUser())) return false;
    }
    if (getRepeatEnd()
        != other.getRepeatEnd()) return false;
    if (getGroupId()
        != other.getGroupId()) return false;
    if (getRoomFanTicketCount()
        != other.getRoomFanTicketCount()) return false;
    if (hasGift() != other.hasGift()) return false;
    if (hasGift()) {
      if (!getGift()
          .equals(other.getGift())) return false;
    }
    if (!getLogId()
        .equals(other.getLogId())) return false;
    if (getSendType()
        != other.getSendType()) return false;
    if (hasTrayDisplayText() != other.hasTrayDisplayText()) return false;
    if (hasTrayDisplayText()) {
      if (!getTrayDisplayText()
          .equals(other.getTrayDisplayText())) return false;
    }
    if (getForceDisplayEffects()
        != other.getForceDisplayEffects()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommon()) {
      hash = (37 * hash) + COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getCommon().hashCode();
    }
    hash = (37 * hash) + GIFTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGiftId());
    hash = (37 * hash) + FANTICKETCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFanTicketCount());
    hash = (37 * hash) + GROUPCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupCount());
    hash = (37 * hash) + REPEATCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRepeatCount());
    hash = (37 * hash) + COMBOCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getComboCount());
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasToUser()) {
      hash = (37 * hash) + TOUSER_FIELD_NUMBER;
      hash = (53 * hash) + getToUser().hashCode();
    }
    hash = (37 * hash) + REPEATEND_FIELD_NUMBER;
    hash = (53 * hash) + getRepeatEnd();
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupId());
    hash = (37 * hash) + ROOMFANTICKETCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoomFanTicketCount());
    if (hasGift()) {
      hash = (37 * hash) + GIFT_FIELD_NUMBER;
      hash = (53 * hash) + getGift().hashCode();
    }
    hash = (37 * hash) + LOGID_FIELD_NUMBER;
    hash = (53 * hash) + getLogId().hashCode();
    hash = (37 * hash) + SENDTYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSendType());
    if (hasTrayDisplayText()) {
      hash = (37 * hash) + TRAYDISPLAYTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getTrayDisplayText().hashCode();
    }
    hash = (37 * hash) + FORCEDISPLAYEFFECTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getForceDisplayEffects());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 礼物消息
   * </pre>
   *
   * Protobuf type {@code GiftMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GiftMessage)
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage.class, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage.Builder.class);
    }

    // Construct using tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommonFieldBuilder();
        getUserFieldBuilder();
        getToUserFieldBuilder();
        getGiftFieldBuilder();
        getTrayDisplayTextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      giftId_ = 0L;
      fanTicketCount_ = 0L;
      groupCount_ = 0L;
      repeatCount_ = 0L;
      comboCount_ = 0L;
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      toUser_ = null;
      if (toUserBuilder_ != null) {
        toUserBuilder_.dispose();
        toUserBuilder_ = null;
      }
      repeatEnd_ = 0;
      groupId_ = 0L;
      roomFanTicketCount_ = 0L;
      gift_ = null;
      if (giftBuilder_ != null) {
        giftBuilder_.dispose();
        giftBuilder_ = null;
      }
      logId_ = "";
      sendType_ = 0L;
      trayDisplayText_ = null;
      if (trayDisplayTextBuilder_ != null) {
        trayDisplayTextBuilder_.dispose();
        trayDisplayTextBuilder_ = null;
      }
      forceDisplayEffects_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Tiktok.internal_static_GiftMessage_descriptor;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage getDefaultInstanceForType() {
      return tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage.getDefaultInstance();
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage build() {
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage buildPartial() {
      tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage result = new tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.common_ = commonBuilder_ == null
            ? common_
            : commonBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.giftId_ = giftId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.fanTicketCount_ = fanTicketCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.groupCount_ = groupCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.repeatCount_ = repeatCount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.comboCount_ = comboCount_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.user_ = userBuilder_ == null
            ? user_
            : userBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.toUser_ = toUserBuilder_ == null
            ? toUser_
            : toUserBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.repeatEnd_ = repeatEnd_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.roomFanTicketCount_ = roomFanTicketCount_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.gift_ = giftBuilder_ == null
            ? gift_
            : giftBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.logId_ = logId_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.sendType_ = sendType_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.trayDisplayText_ = trayDisplayTextBuilder_ == null
            ? trayDisplayText_
            : trayDisplayTextBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.forceDisplayEffects_ = forceDisplayEffects_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage) {
        return mergeFrom((tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage other) {
      if (other == tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage.getDefaultInstance()) return this;
      if (other.hasCommon()) {
        mergeCommon(other.getCommon());
      }
      if (other.getGiftId() != 0L) {
        setGiftId(other.getGiftId());
      }
      if (other.getFanTicketCount() != 0L) {
        setFanTicketCount(other.getFanTicketCount());
      }
      if (other.getGroupCount() != 0L) {
        setGroupCount(other.getGroupCount());
      }
      if (other.getRepeatCount() != 0L) {
        setRepeatCount(other.getRepeatCount());
      }
      if (other.getComboCount() != 0L) {
        setComboCount(other.getComboCount());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasToUser()) {
        mergeToUser(other.getToUser());
      }
      if (other.getRepeatEnd() != 0) {
        setRepeatEnd(other.getRepeatEnd());
      }
      if (other.getGroupId() != 0L) {
        setGroupId(other.getGroupId());
      }
      if (other.getRoomFanTicketCount() != 0L) {
        setRoomFanTicketCount(other.getRoomFanTicketCount());
      }
      if (other.hasGift()) {
        mergeGift(other.getGift());
      }
      if (!other.getLogId().isEmpty()) {
        logId_ = other.logId_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getSendType() != 0L) {
        setSendType(other.getSendType());
      }
      if (other.hasTrayDisplayText()) {
        mergeTrayDisplayText(other.getTrayDisplayText());
      }
      if (other.getForceDisplayEffects() != 0L) {
        setForceDisplayEffects(other.getForceDisplayEffects());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCommonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              giftId_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              fanTicketCount_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              groupCount_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              repeatCount_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              comboCount_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getToUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              repeatEnd_ = input.readUInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 88: {
              groupId_ = input.readUInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 88
            case 104: {
              roomFanTicketCount_ = input.readUInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 104
            case 122: {
              input.readMessage(
                  getGiftFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 122
            case 130: {
              logId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 130
            case 136: {
              sendType_ = input.readUInt64();
              bitField0_ |= 0x00002000;
              break;
            } // case 136
            case 154: {
              input.readMessage(
                  getTrayDisplayTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00004000;
              break;
            } // case 154
            case 272: {
              forceDisplayEffects_ = input.readUInt64();
              bitField0_ |= 0x00008000;
              break;
            } // case 272
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common common_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder> commonBuilder_;
    /**
     * <code>.Common common = 1;</code>
     * @return Whether the common field is set.
     */
    public boolean hasCommon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Common common = 1;</code>
     * @return The common.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getCommon() {
      if (commonBuilder_ == null) {
        return common_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.getDefaultInstance() : common_;
      } else {
        return commonBuilder_.getMessage();
      }
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder setCommon(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common value) {
      if (commonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        common_ = value;
      } else {
        commonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder setCommon(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.Builder builderForValue) {
      if (commonBuilder_ == null) {
        common_ = builderForValue.build();
      } else {
        commonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder mergeCommon(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common value) {
      if (commonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          common_ != null &&
          common_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.getDefaultInstance()) {
          getCommonBuilder().mergeFrom(value);
        } else {
          common_ = value;
        }
      } else {
        commonBuilder_.mergeFrom(value);
      }
      if (common_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder clearCommon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.Builder getCommonBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder getCommonOrBuilder() {
      if (commonBuilder_ != null) {
        return commonBuilder_.getMessageOrBuilder();
      } else {
        return common_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.getDefaultInstance() : common_;
      }
    }
    /**
     * <code>.Common common = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder> 
        getCommonFieldBuilder() {
      if (commonBuilder_ == null) {
        commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder>(
                getCommon(),
                getParentForChildren(),
                isClean());
        common_ = null;
      }
      return commonBuilder_;
    }

    private long giftId_ ;
    /**
     * <code>uint64 giftId = 2;</code>
     * @return The giftId.
     */
    @java.lang.Override
    public long getGiftId() {
      return giftId_;
    }
    /**
     * <code>uint64 giftId = 2;</code>
     * @param value The giftId to set.
     * @return This builder for chaining.
     */
    public Builder setGiftId(long value) {

      giftId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 giftId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGiftId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      giftId_ = 0L;
      onChanged();
      return this;
    }

    private long fanTicketCount_ ;
    /**
     * <code>uint64 fanTicketCount = 3;</code>
     * @return The fanTicketCount.
     */
    @java.lang.Override
    public long getFanTicketCount() {
      return fanTicketCount_;
    }
    /**
     * <code>uint64 fanTicketCount = 3;</code>
     * @param value The fanTicketCount to set.
     * @return This builder for chaining.
     */
    public Builder setFanTicketCount(long value) {

      fanTicketCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 fanTicketCount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFanTicketCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      fanTicketCount_ = 0L;
      onChanged();
      return this;
    }

    private long groupCount_ ;
    /**
     * <code>uint64 groupCount = 4;</code>
     * @return The groupCount.
     */
    @java.lang.Override
    public long getGroupCount() {
      return groupCount_;
    }
    /**
     * <code>uint64 groupCount = 4;</code>
     * @param value The groupCount to set.
     * @return This builder for chaining.
     */
    public Builder setGroupCount(long value) {

      groupCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 groupCount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      groupCount_ = 0L;
      onChanged();
      return this;
    }

    private long repeatCount_ ;
    /**
     * <code>uint64 repeatCount = 5;</code>
     * @return The repeatCount.
     */
    @java.lang.Override
    public long getRepeatCount() {
      return repeatCount_;
    }
    /**
     * <code>uint64 repeatCount = 5;</code>
     * @param value The repeatCount to set.
     * @return This builder for chaining.
     */
    public Builder setRepeatCount(long value) {

      repeatCount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 repeatCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepeatCount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      repeatCount_ = 0L;
      onChanged();
      return this;
    }

    private long comboCount_ ;
    /**
     * <code>uint64 comboCount = 6;</code>
     * @return The comboCount.
     */
    @java.lang.Override
    public long getComboCount() {
      return comboCount_;
    }
    /**
     * <code>uint64 comboCount = 6;</code>
     * @param value The comboCount to set.
     * @return This builder for chaining.
     */
    public Builder setComboCount(long value) {

      comboCount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 comboCount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearComboCount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      comboCount_ = 0L;
      onChanged();
      return this;
    }

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder> userBuilder_;
    /**
     * <code>.User user = 7;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.User user = 7;</code>
     * @return The user.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.User user = 7;</code>
     */
    public Builder setUser(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
      } else {
        userBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.User user = 7;</code>
     */
    public Builder setUser(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.User user = 7;</code>
     */
    public Builder mergeUser(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User value) {
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          user_ != null &&
          user_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance()) {
          getUserBuilder().mergeFrom(value);
        } else {
          user_ = value;
        }
      } else {
        userBuilder_.mergeFrom(value);
      }
      if (user_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.User user = 7;</code>
     */
    public Builder clearUser() {
      bitField0_ = (bitField0_ & ~0x00000040);
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.User user = 7;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder getUserBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.User user = 7;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.User user = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User toUser_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder> toUserBuilder_;
    /**
     * <code>.User toUser = 8;</code>
     * @return Whether the toUser field is set.
     */
    public boolean hasToUser() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.User toUser = 8;</code>
     * @return The toUser.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getToUser() {
      if (toUserBuilder_ == null) {
        return toUser_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : toUser_;
      } else {
        return toUserBuilder_.getMessage();
      }
    }
    /**
     * <code>.User toUser = 8;</code>
     */
    public Builder setToUser(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User value) {
      if (toUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toUser_ = value;
      } else {
        toUserBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.User toUser = 8;</code>
     */
    public Builder setToUser(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder builderForValue) {
      if (toUserBuilder_ == null) {
        toUser_ = builderForValue.build();
      } else {
        toUserBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.User toUser = 8;</code>
     */
    public Builder mergeToUser(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User value) {
      if (toUserBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          toUser_ != null &&
          toUser_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance()) {
          getToUserBuilder().mergeFrom(value);
        } else {
          toUser_ = value;
        }
      } else {
        toUserBuilder_.mergeFrom(value);
      }
      if (toUser_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.User toUser = 8;</code>
     */
    public Builder clearToUser() {
      bitField0_ = (bitField0_ & ~0x00000080);
      toUser_ = null;
      if (toUserBuilder_ != null) {
        toUserBuilder_.dispose();
        toUserBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.User toUser = 8;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder getToUserBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getToUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.User toUser = 8;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getToUserOrBuilder() {
      if (toUserBuilder_ != null) {
        return toUserBuilder_.getMessageOrBuilder();
      } else {
        return toUser_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.getDefaultInstance() : toUser_;
      }
    }
    /**
     * <code>.User toUser = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder> 
        getToUserFieldBuilder() {
      if (toUserBuilder_ == null) {
        toUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder>(
                getToUser(),
                getParentForChildren(),
                isClean());
        toUser_ = null;
      }
      return toUserBuilder_;
    }

    private int repeatEnd_ ;
    /**
     * <code>uint32 repeatEnd = 9;</code>
     * @return The repeatEnd.
     */
    @java.lang.Override
    public int getRepeatEnd() {
      return repeatEnd_;
    }
    /**
     * <code>uint32 repeatEnd = 9;</code>
     * @param value The repeatEnd to set.
     * @return This builder for chaining.
     */
    public Builder setRepeatEnd(int value) {

      repeatEnd_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 repeatEnd = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepeatEnd() {
      bitField0_ = (bitField0_ & ~0x00000100);
      repeatEnd_ = 0;
      onChanged();
      return this;
    }

    private long groupId_ ;
    /**
     * <pre>
     *  TextEffect textEffect = 10;
     * </pre>
     *
     * <code>uint64 groupId = 11;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <pre>
     *  TextEffect textEffect = 10;
     * </pre>
     *
     * <code>uint64 groupId = 11;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(long value) {

      groupId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  TextEffect textEffect = 10;
     * </pre>
     *
     * <code>uint64 groupId = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      bitField0_ = (bitField0_ & ~0x00000200);
      groupId_ = 0L;
      onChanged();
      return this;
    }

    private long roomFanTicketCount_ ;
    /**
     * <pre>
     *  uint64 incomeTaskgifts = 12;
     * </pre>
     *
     * <code>uint64 roomFanTicketCount = 13;</code>
     * @return The roomFanTicketCount.
     */
    @java.lang.Override
    public long getRoomFanTicketCount() {
      return roomFanTicketCount_;
    }
    /**
     * <pre>
     *  uint64 incomeTaskgifts = 12;
     * </pre>
     *
     * <code>uint64 roomFanTicketCount = 13;</code>
     * @param value The roomFanTicketCount to set.
     * @return This builder for chaining.
     */
    public Builder setRoomFanTicketCount(long value) {

      roomFanTicketCount_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  uint64 incomeTaskgifts = 12;
     * </pre>
     *
     * <code>uint64 roomFanTicketCount = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomFanTicketCount() {
      bitField0_ = (bitField0_ & ~0x00000400);
      roomFanTicketCount_ = 0L;
      onChanged();
      return this;
    }

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct gift_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStructOrBuilder> giftBuilder_;
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     * @return Whether the gift field is set.
     */
    public boolean hasGift() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     * @return The gift.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct getGift() {
      if (giftBuilder_ == null) {
        return gift_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.getDefaultInstance() : gift_;
      } else {
        return giftBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     */
    public Builder setGift(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct value) {
      if (giftBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gift_ = value;
      } else {
        giftBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     */
    public Builder setGift(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.Builder builderForValue) {
      if (giftBuilder_ == null) {
        gift_ = builderForValue.build();
      } else {
        giftBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     */
    public Builder mergeGift(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct value) {
      if (giftBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          gift_ != null &&
          gift_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.getDefaultInstance()) {
          getGiftBuilder().mergeFrom(value);
        } else {
          gift_ = value;
        }
      } else {
        giftBuilder_.mergeFrom(value);
      }
      if (gift_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     */
    public Builder clearGift() {
      bitField0_ = (bitField0_ & ~0x00000800);
      gift_ = null;
      if (giftBuilder_ != null) {
        giftBuilder_.dispose();
        giftBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.Builder getGiftBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getGiftFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStructOrBuilder getGiftOrBuilder() {
      if (giftBuilder_ != null) {
        return giftBuilder_.getMessageOrBuilder();
      } else {
        return gift_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.getDefaultInstance() : gift_;
      }
    }
    /**
     * <pre>
     *  GiftIMPriority priority = 14;
     * </pre>
     *
     * <code>.GiftStruct gift = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStructOrBuilder> 
        getGiftFieldBuilder() {
      if (giftBuilder_ == null) {
        giftBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStructOrBuilder>(
                getGift(),
                getParentForChildren(),
                isClean());
        gift_ = null;
      }
      return giftBuilder_;
    }

    private java.lang.Object logId_ = "";
    /**
     * <code>string logId = 16;</code>
     * @return The logId.
     */
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string logId = 16;</code>
     * @return The bytes for logId.
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string logId = 16;</code>
     * @param value The logId to set.
     * @return This builder for chaining.
     */
    public Builder setLogId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      logId_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string logId = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogId() {
      logId_ = getDefaultInstance().getLogId();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string logId = 16;</code>
     * @param value The bytes for logId to set.
     * @return This builder for chaining.
     */
    public Builder setLogIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      logId_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private long sendType_ ;
    /**
     * <code>uint64 sendType = 17;</code>
     * @return The sendType.
     */
    @java.lang.Override
    public long getSendType() {
      return sendType_;
    }
    /**
     * <code>uint64 sendType = 17;</code>
     * @param value The sendType to set.
     * @return This builder for chaining.
     */
    public Builder setSendType(long value) {

      sendType_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 sendType = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearSendType() {
      bitField0_ = (bitField0_ & ~0x00002000);
      sendType_ = 0L;
      onChanged();
      return this;
    }

    private tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text trayDisplayText_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder> trayDisplayTextBuilder_;
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     * @return Whether the trayDisplayText field is set.
     */
    public boolean hasTrayDisplayText() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     * @return The trayDisplayText.
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getTrayDisplayText() {
      if (trayDisplayTextBuilder_ == null) {
        return trayDisplayText_ == null ? tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : trayDisplayText_;
      } else {
        return trayDisplayTextBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     */
    public Builder setTrayDisplayText(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text value) {
      if (trayDisplayTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trayDisplayText_ = value;
      } else {
        trayDisplayTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     */
    public Builder setTrayDisplayText(
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder builderForValue) {
      if (trayDisplayTextBuilder_ == null) {
        trayDisplayText_ = builderForValue.build();
      } else {
        trayDisplayTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     */
    public Builder mergeTrayDisplayText(tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text value) {
      if (trayDisplayTextBuilder_ == null) {
        if (((bitField0_ & 0x00004000) != 0) &&
          trayDisplayText_ != null &&
          trayDisplayText_ != tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance()) {
          getTrayDisplayTextBuilder().mergeFrom(value);
        } else {
          trayDisplayText_ = value;
        }
      } else {
        trayDisplayTextBuilder_.mergeFrom(value);
      }
      if (trayDisplayText_ != null) {
        bitField0_ |= 0x00004000;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     */
    public Builder clearTrayDisplayText() {
      bitField0_ = (bitField0_ & ~0x00004000);
      trayDisplayText_ = null;
      if (trayDisplayTextBuilder_ != null) {
        trayDisplayTextBuilder_.dispose();
        trayDisplayTextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder getTrayDisplayTextBuilder() {
      bitField0_ |= 0x00004000;
      onChanged();
      return getTrayDisplayTextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     */
    public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getTrayDisplayTextOrBuilder() {
      if (trayDisplayTextBuilder_ != null) {
        return trayDisplayTextBuilder_.getMessageOrBuilder();
      } else {
        return trayDisplayText_ == null ?
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.getDefaultInstance() : trayDisplayText_;
      }
    }
    /**
     * <pre>
     *  PublicAreaCommon publicAreaCommon = 18;
     * </pre>
     *
     * <code>.Text trayDisplayText = 19;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder> 
        getTrayDisplayTextFieldBuilder() {
      if (trayDisplayTextBuilder_ == null) {
        trayDisplayTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text.Builder, tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder>(
                getTrayDisplayText(),
                getParentForChildren(),
                isClean());
        trayDisplayText_ = null;
      }
      return trayDisplayTextBuilder_;
    }

    private long forceDisplayEffects_ ;
    /**
     * <pre>
     *  uint64 bannedDisplayEffects = 20;
     *  //  GiftTrayInfo trayInfo = 21;
     *  //  AssetEffectMixInfo assetEffectMixInfo = 22;
     *  bool displayForSelf = 25;
     *  string interactGiftInfo = 26;
     *  string diyItemInfo = 27;
     *  repeated uint64 minAssetSetList = 28;
     *  uint64 totalCount = 29;
     *  uint32 clientGiftSource = 30;
     *  //  AnchorGiftData anchorGift = 31;
     *  repeated uint64 toUserIdsList = 32;
     *  uint64 sendTime = 33;
     * </pre>
     *
     * <code>uint64 forceDisplayEffects = 34;</code>
     * @return The forceDisplayEffects.
     */
    @java.lang.Override
    public long getForceDisplayEffects() {
      return forceDisplayEffects_;
    }
    /**
     * <pre>
     *  uint64 bannedDisplayEffects = 20;
     *  //  GiftTrayInfo trayInfo = 21;
     *  //  AssetEffectMixInfo assetEffectMixInfo = 22;
     *  bool displayForSelf = 25;
     *  string interactGiftInfo = 26;
     *  string diyItemInfo = 27;
     *  repeated uint64 minAssetSetList = 28;
     *  uint64 totalCount = 29;
     *  uint32 clientGiftSource = 30;
     *  //  AnchorGiftData anchorGift = 31;
     *  repeated uint64 toUserIdsList = 32;
     *  uint64 sendTime = 33;
     * </pre>
     *
     * <code>uint64 forceDisplayEffects = 34;</code>
     * @param value The forceDisplayEffects to set.
     * @return This builder for chaining.
     */
    public Builder setForceDisplayEffects(long value) {

      forceDisplayEffects_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  uint64 bannedDisplayEffects = 20;
     *  //  GiftTrayInfo trayInfo = 21;
     *  //  AssetEffectMixInfo assetEffectMixInfo = 22;
     *  bool displayForSelf = 25;
     *  string interactGiftInfo = 26;
     *  string diyItemInfo = 27;
     *  repeated uint64 minAssetSetList = 28;
     *  uint64 totalCount = 29;
     *  uint32 clientGiftSource = 30;
     *  //  AnchorGiftData anchorGift = 31;
     *  repeated uint64 toUserIdsList = 32;
     *  uint64 sendTime = 33;
     * </pre>
     *
     * <code>uint64 forceDisplayEffects = 34;</code>
     * @return This builder for chaining.
     */
    public Builder clearForceDisplayEffects() {
      bitField0_ = (bitField0_ & ~0x00008000);
      forceDisplayEffects_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GiftMessage)
  }

  // @@protoc_insertion_point(class_scope:GiftMessage)
  private static final tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage();
  }

  public static tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GiftMessage>
      PARSER = new com.google.protobuf.AbstractParser<GiftMessage>() {
    @java.lang.Override
    public GiftMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GiftMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GiftMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

