// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

public interface GiftMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GiftMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>uint64 giftId = 2;</code>
   * @return The giftId.
   */
  long getGiftId();

  /**
   * <code>uint64 fanTicketCount = 3;</code>
   * @return The fanTicketCount.
   */
  long getFanTicketCount();

  /**
   * <code>uint64 groupCount = 4;</code>
   * @return The groupCount.
   */
  long getGroupCount();

  /**
   * <code>uint64 repeatCount = 5;</code>
   * @return The repeatCount.
   */
  long getRepeatCount();

  /**
   * <code>uint64 comboCount = 6;</code>
   * @return The comboCount.
   */
  long getComboCount();

  /**
   * <code>.User user = 7;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 7;</code>
   * @return The user.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getUser();
  /**
   * <code>.User user = 7;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.User toUser = 8;</code>
   * @return Whether the toUser field is set.
   */
  boolean hasToUser();
  /**
   * <code>.User toUser = 8;</code>
   * @return The toUser.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getToUser();
  /**
   * <code>.User toUser = 8;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getToUserOrBuilder();

  /**
   * <code>uint32 repeatEnd = 9;</code>
   * @return The repeatEnd.
   */
  int getRepeatEnd();

  /**
   * <pre>
   *  TextEffect textEffect = 10;
   * </pre>
   *
   * <code>uint64 groupId = 11;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <pre>
   *  uint64 incomeTaskgifts = 12;
   * </pre>
   *
   * <code>uint64 roomFanTicketCount = 13;</code>
   * @return The roomFanTicketCount.
   */
  long getRoomFanTicketCount();

  /**
   * <pre>
   *  GiftIMPriority priority = 14;
   * </pre>
   *
   * <code>.GiftStruct gift = 15;</code>
   * @return Whether the gift field is set.
   */
  boolean hasGift();
  /**
   * <pre>
   *  GiftIMPriority priority = 14;
   * </pre>
   *
   * <code>.GiftStruct gift = 15;</code>
   * @return The gift.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStruct getGift();
  /**
   * <pre>
   *  GiftIMPriority priority = 14;
   * </pre>
   *
   * <code>.GiftStruct gift = 15;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.GiftStructOrBuilder getGiftOrBuilder();

  /**
   * <code>string logId = 16;</code>
   * @return The logId.
   */
  java.lang.String getLogId();
  /**
   * <code>string logId = 16;</code>
   * @return The bytes for logId.
   */
  com.google.protobuf.ByteString
      getLogIdBytes();

  /**
   * <code>uint64 sendType = 17;</code>
   * @return The sendType.
   */
  long getSendType();

  /**
   * <pre>
   *  PublicAreaCommon publicAreaCommon = 18;
   * </pre>
   *
   * <code>.Text trayDisplayText = 19;</code>
   * @return Whether the trayDisplayText field is set.
   */
  boolean hasTrayDisplayText();
  /**
   * <pre>
   *  PublicAreaCommon publicAreaCommon = 18;
   * </pre>
   *
   * <code>.Text trayDisplayText = 19;</code>
   * @return The trayDisplayText.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getTrayDisplayText();
  /**
   * <pre>
   *  PublicAreaCommon publicAreaCommon = 18;
   * </pre>
   *
   * <code>.Text trayDisplayText = 19;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getTrayDisplayTextOrBuilder();

  /**
   * <pre>
   *  uint64 bannedDisplayEffects = 20;
   *  //  GiftTrayInfo trayInfo = 21;
   *  //  AssetEffectMixInfo assetEffectMixInfo = 22;
   *  bool displayForSelf = 25;
   *  string interactGiftInfo = 26;
   *  string diyItemInfo = 27;
   *  repeated uint64 minAssetSetList = 28;
   *  uint64 totalCount = 29;
   *  uint32 clientGiftSource = 30;
   *  //  AnchorGiftData anchorGift = 31;
   *  repeated uint64 toUserIdsList = 32;
   *  uint64 sendTime = 33;
   * </pre>
   *
   * <code>uint64 forceDisplayEffects = 34;</code>
   * @return The forceDisplayEffects.
   */
  long getForceDisplayEffects();
}
