// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

public interface MemberMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MemberMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 2;</code>
   * @return The user.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getUser();
  /**
   * <code>.User user = 2;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>uint64 memberCount = 3;</code>
   * @return The memberCount.
   */
  long getMemberCount();

  /**
   * <pre>
   *  User operator = 4;
   *  bool isSetToAdmin = 5;
   *  bool isTopUser = 6;
   *  uint64 rankScore = 7;
   *  uint64 topUserNo = 8;
   *  uint64 enterType = 9;
   * </pre>
   *
   * <code>uint64 action = 10;</code>
   * @return The action.
   */
  long getAction();

  /**
   * <pre>
   *  string actionDescription = 11;
   *  uint64 userId = 12;
   *  EffectConfig effectConfig = 13;
   *  string popStr = 14;
   *  EffectConfig enterEffectConfig = 15;
   *  Image backgroundImage = 16;
   *  Image backgroundImageV2 = 17;
   * </pre>
   *
   * <code>.Text anchorDisplayText = 18;</code>
   * @return Whether the anchorDisplayText field is set.
   */
  boolean hasAnchorDisplayText();
  /**
   * <pre>
   *  string actionDescription = 11;
   *  uint64 userId = 12;
   *  EffectConfig effectConfig = 13;
   *  string popStr = 14;
   *  EffectConfig enterEffectConfig = 15;
   *  Image backgroundImage = 16;
   *  Image backgroundImageV2 = 17;
   * </pre>
   *
   * <code>.Text anchorDisplayText = 18;</code>
   * @return The anchorDisplayText.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Text getAnchorDisplayText();
  /**
   * <pre>
   *  string actionDescription = 11;
   *  uint64 userId = 12;
   *  EffectConfig effectConfig = 13;
   *  string popStr = 14;
   *  EffectConfig enterEffectConfig = 15;
   *  Image backgroundImage = 16;
   *  Image backgroundImageV2 = 17;
   * </pre>
   *
   * <code>.Text anchorDisplayText = 18;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.TextOrBuilder getAnchorDisplayTextOrBuilder();
}
