// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

public interface TextPieceUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextPieceUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  bool withColon = 2;
   *  bool self_show_real_name = 3;
   *  uint32 left_show_extension = 4;
   *  string left_additional_content = 5;
   *  string right_additional_content = 6;
   * </pre>
   *
   * <code>.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <pre>
   *  bool withColon = 2;
   *  bool self_show_real_name = 3;
   *  uint32 left_show_extension = 4;
   *  string left_additional_content = 5;
   *  string right_additional_content = 6;
   * </pre>
   *
   * <code>.User user = 1;</code>
   * @return The user.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.User getUser();
  /**
   * <pre>
   *  bool withColon = 2;
   *  bool self_show_real_name = 3;
   *  uint32 left_show_extension = 4;
   *  string left_additional_content = 5;
   *  string right_additional_content = 6;
   * </pre>
   *
   * <code>.User user = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.UserOrBuilder getUserOrBuilder();
}
