// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

public interface TextEffectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextEffect)
    com.google.protobuf.MessageOrBuilder {
}
