// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *  uint64 shortId = 2;
   * </pre>
   *
   * <code>string nickName = 3;</code>
   * @return The nickName.
   */
  java.lang.String getNickName();
  /**
   * <pre>
   *  uint64 shortId = 2;
   * </pre>
   *
   * <code>string nickName = 3;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <pre>
   *  uint32 gender = 4;
   *  string Signature = 5;
   *  uint32 Level = 6;
   *  uint64 Birthday = 7;
   *  string Telephone = 8;
   * </pre>
   *
   * <code>.Image AvatarThumb = 9;</code>
   * @return Whether the avatarThumb field is set.
   */
  boolean hasAvatarThumb();
  /**
   * <pre>
   *  uint32 gender = 4;
   *  string Signature = 5;
   *  uint32 Level = 6;
   *  uint64 Birthday = 7;
   *  string Telephone = 8;
   * </pre>
   *
   * <code>.Image AvatarThumb = 9;</code>
   * @return The avatarThumb.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getAvatarThumb();
  /**
   * <pre>
   *  uint32 gender = 4;
   *  string Signature = 5;
   *  uint32 Level = 6;
   *  uint64 Birthday = 7;
   *  string Telephone = 8;
   * </pre>
   *
   * <code>.Image AvatarThumb = 9;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getAvatarThumbOrBuilder();

  /**
   * <code>.Image AvatarMedium = 10;</code>
   * @return Whether the avatarMedium field is set.
   */
  boolean hasAvatarMedium();
  /**
   * <code>.Image AvatarMedium = 10;</code>
   * @return The avatarMedium.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getAvatarMedium();
  /**
   * <code>.Image AvatarMedium = 10;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getAvatarMediumOrBuilder();

  /**
   * <code>.Image AvatarLarge = 11;</code>
   * @return Whether the avatarLarge field is set.
   */
  boolean hasAvatarLarge();
  /**
   * <code>.Image AvatarLarge = 11;</code>
   * @return The avatarLarge.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getAvatarLarge();
  /**
   * <code>.Image AvatarLarge = 11;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getAvatarLargeOrBuilder();

  /**
   * <pre>
   *  bool Verified = 12;
   *  uint32 Experience = 13;
   *  string city = 14;
   *  int32 Status = 15;
   *  uint64 CreateTime = 16;
   *  uint64 ModifyTime = 17;
   *  uint32 Secret = 18;
   *  string ShareQrcodeUri = 19;
   *  uint32 IncomeSharePercent = 20;
   * </pre>
   *
   * <code>repeated .Image BadgeImageList = 21;</code>
   */
  java.util.List<tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image> 
      getBadgeImageListList();
  /**
   * <pre>
   *  bool Verified = 12;
   *  uint32 Experience = 13;
   *  string city = 14;
   *  int32 Status = 15;
   *  uint64 CreateTime = 16;
   *  uint64 ModifyTime = 17;
   *  uint32 Secret = 18;
   *  string ShareQrcodeUri = 19;
   *  uint32 IncomeSharePercent = 20;
   * </pre>
   *
   * <code>repeated .Image BadgeImageList = 21;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.Image getBadgeImageList(int index);
  /**
   * <pre>
   *  bool Verified = 12;
   *  uint32 Experience = 13;
   *  string city = 14;
   *  int32 Status = 15;
   *  uint64 CreateTime = 16;
   *  uint64 ModifyTime = 17;
   *  uint32 Secret = 18;
   *  string ShareQrcodeUri = 19;
   *  uint32 IncomeSharePercent = 20;
   * </pre>
   *
   * <code>repeated .Image BadgeImageList = 21;</code>
   */
  int getBadgeImageListCount();
  /**
   * <pre>
   *  bool Verified = 12;
   *  uint32 Experience = 13;
   *  string city = 14;
   *  int32 Status = 15;
   *  uint64 CreateTime = 16;
   *  uint64 ModifyTime = 17;
   *  uint32 Secret = 18;
   *  string ShareQrcodeUri = 19;
   *  uint32 IncomeSharePercent = 20;
   * </pre>
   *
   * <code>repeated .Image BadgeImageList = 21;</code>
   */
  java.util.List<? extends tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder> 
      getBadgeImageListOrBuilderList();
  /**
   * <pre>
   *  bool Verified = 12;
   *  uint32 Experience = 13;
   *  string city = 14;
   *  int32 Status = 15;
   *  uint64 CreateTime = 16;
   *  uint64 ModifyTime = 17;
   *  uint32 Secret = 18;
   *  string ShareQrcodeUri = 19;
   *  uint32 IncomeSharePercent = 20;
   * </pre>
   *
   * <code>repeated .Image BadgeImageList = 21;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.ImageOrBuilder getBadgeImageListOrBuilder(
      int index);

  /**
   * <code>.FollowInfo FollowInfo = 22;</code>
   * @return Whether the followInfo field is set.
   */
  boolean hasFollowInfo();
  /**
   * <code>.FollowInfo FollowInfo = 22;</code>
   * @return The followInfo.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.FollowInfo getFollowInfo();
  /**
   * <code>.FollowInfo FollowInfo = 22;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.FollowInfoOrBuilder getFollowInfoOrBuilder();

  /**
   * <code>.PayGrade PayGrade = 23;</code>
   * @return Whether the payGrade field is set.
   */
  boolean hasPayGrade();
  /**
   * <code>.PayGrade PayGrade = 23;</code>
   * @return The payGrade.
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.PayGrade getPayGrade();
  /**
   * <code>.PayGrade PayGrade = 23;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.tiktok.protobuf.PayGradeOrBuilder getPayGradeOrBuilder();

  /**
   * <pre>
   *  FansClub FansClub = 24;
   *  //  Border Border = 25;
   *  string SpecialId = 26;
   *  Image AvatarBorder = 27;
   *  Image Medal = 28;
   *  repeated Image RealTimeIconsList = 29;
   * </pre>
   *
   * <code>string displayId = 38;</code>
   * @return The displayId.
   */
  java.lang.String getDisplayId();
  /**
   * <pre>
   *  FansClub FansClub = 24;
   *  //  Border Border = 25;
   *  string SpecialId = 26;
   *  Image AvatarBorder = 27;
   *  Image Medal = 28;
   *  repeated Image RealTimeIconsList = 29;
   * </pre>
   *
   * <code>string displayId = 38;</code>
   * @return The bytes for displayId.
   */
  com.google.protobuf.ByteString
      getDisplayIdBytes();

  /**
   * <code>string secUid = 46;</code>
   * @return The secUid.
   */
  java.lang.String getSecUid();
  /**
   * <code>string secUid = 46;</code>
   * @return The bytes for secUid.
   */
  com.google.protobuf.ByteString
      getSecUidBytes();

  /**
   * <pre>
   *  uint64 fanTicketCount = 1022;
   * </pre>
   *
   * <code>string idStr = 1028;</code>
   * @return The idStr.
   */
  java.lang.String getIdStr();
  /**
   * <pre>
   *  uint64 fanTicketCount = 1022;
   * </pre>
   *
   * <code>string idStr = 1028;</code>
   * @return The bytes for idStr.
   */
  com.google.protobuf.ByteString
      getIdStrBytes();
}
